resources:
- name: resource-test01
  type: git
  source:
    uri: https://github.com/buzztroll/concoursebidnes.git

jobs:
- name: buzzstart
  public: true
  plan: 
  - get: resource-test01
  - task: install-apache
    file: resource-test01/test01/install-apache.yml
  - task: set-data
    file: resource-test01/test01/set-data.yml
